/**
 * phone-api
 * Jumia Exercise
 *
 * OpenAPI spec version: 1.0
 * Contact: aya.abdelmaqsoud@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GenericResponse } from './GenericResponse'; 

export interface ErrorResponse extends GenericResponse {
}

